store data in db
ctc-uci/authentication-backend pull request #2
Opened 2022-02-04 19:41 UTC by ctc-devops

After a user account is created, their information (email, firebase user id, role) should be stored in a DB. Add a route to do this.
closes #1

2022-02-04 20:37 UTC, ctc-devops commented on routes/users.jsx
> +  console.log('request made to /:id route');
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-02-04 20:37 UTC, ctc-devops commented on routes/users.jsx
> +  console.log('POST /user/create in');
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-02-04 20:37 UTC, ctc-devops commented on routes/users.jsx
> +  console.log(req.body);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-02-04 20:37 UTC, ctc-devops commented on routes/users.jsx
> +    console.log(err);
⚠️ **[eslint]** <[no-console](https://eslint.org/docs/rules/no-console)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Unexpected console statement.

2022-02-06 02:59 UTC, Vakhshoori101 requested changes
Just a heads up, this is vulnerable to SQL injections.
Please follow validation coding practices seen in [here](https://github.com/ctc-uci/waymakers-backend/blob/master/routes/inventory/category.js)
Using a combination of type verification such as `isInteger` method and [parametrized queries](https://node-postgres.com/features/queries#Parameterized%20query)

2022-02-06 02:59 UTC, Vakhshoori101 commented on routes/users.js
> +userRouter.get('/:email', async (req, res) => {
please change to firebase user ID rather than email

2022-02-07 01:29 UTC, ZubairSidhu approved these changes

2022-02-07 01:38 UTC, merged